apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsdeck
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/Oriya-Ze/opsdeck.git
      targetRevision: main
      path: helm
      helm:
        valueFiles:
          - values-aws.yaml
          - values-tailscale.yaml
          - $values/helm-values/opsdeck.yaml
    - repoURL: https://github.com/Oriya-Ze/opsdeck-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: opsdeck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
